#!/bin/bash

set -e # Exit if any command errors

# Run setup if eixists
[ -x /etc/services.d/bareos-fd/setup ] && /etc/services.d/bareos-fd/setup

# Copy default config if not exists
[ ! -e /etc/bareos/$BAREOS_FD_CONF_FILE ] && cp /temp/$BAREOS_FD_CONF_FILE /etc/bareos/$BAREOS_FD_CONF_FILE 

# (tail -F /var/log/bareos/bareos.log 2>/dev/null 1>/dev/stdout)&

exec /usr/sbin/bareos-fd -f -c /etc/bareos/$BAREOS_FD_CONF_FILE
