#!/bin/bash

set -e # Exit if any command errors

# Create folder if not exists
[ ! -e /etc/bareos-webui ] && mkdir /etc/bareos-webui

# Copy default config if not exists
[ ! -e /etc/bareos-webui/configuration.ini ] && cp /temp/etc/bareos-webui/configuration.ini /etc/bareos-webui/configuration.ini

# Create directors.ini from template
if [ ! -e /etc/bareos-webui/directors.ini ]; then
  perl -p -e 's/\$\{([^}]+)\}/defined $ENV{$1} ? $ENV{$1} : $&/eg; s/\$\{([^}]+)\}//eg' \
  /temp/etc/bareos-webui/directors.ini.tpl \
  > /etc/bareos-webui/directors.ini
fi


exec /usr/sbin/httpd -D FOREGROUND
