version: 2
jobs:
  build-nginx:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build nginx:7.1
          command: |
            cd nginx-php/7.1
            docker build -t motius/nginx-php:7.1 .
      - run:
          name: Push to hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push motius/nginx-php:7.1

  build-nextcloud:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build nextcloud 13.0.2
          command: |
            cd nextcloud
            docker build -t motius/nextcloud:13.0.2 -f Dockerfile.13.0 .
      - run:
          name: Tag images
          command: |
            docker tag motius/nextcloud:13.0.2 motius/nextcloud:latest
      - run:
          name: Push to hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push motius/nextcloud:latest
            docker push motius/nextcloud:13.0.2

  build-bareos:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build bareos-dir
          command: |
            cd bareos-dir
            docker build -t motius/bareos-dir:17.2 -f Dockerfile .
      - run:
          name: Build bareos-sd
          command: |
            cd bareos-sd
            docker build -t motius/bareos-sd:17.2 -f Dockerfile .
      - run:
          name: Build bareos-fd
          command: |
            cd bareos-fd
            docker build -t motius/bareos-fd:17.2 -f Dockerfile .
      - run:
          name: Build bareos-ui
          command: |
            cd bareos-ui
            docker build -t motius/bareos-ui:17.2 -f Dockerfile .
      - run:
          name: Tag images
          command: |
            docker tag motius/bareos-dir:17.2 motius/bareos-dir
            docker tag motius/bareos-fd:17.2 motius/bareos-fd
            docker tag motius/bareos-sd:17.2 motius/bareos-sd
            docker tag motius/bareos-ui:17.2 motius/bareos-ui
      - run:
          name: Push to hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push motius/bareos-ui:17.2
            docker push motius/bareos-ui:latest
            docker push motius/bareos-dir:17.2
            docker push motius/bareos-dir:latest
            docker push motius/bareos-fd:17.2
            docker push motius/bareos-fd:latest
            docker push motius/bareos-sd:17.2
            docker push motius/bareos-sd:latest

  build-polr:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build polr
          command: |
            cd polr
            docker build -t motius/polr:2.2.0 .
            docker tag motius/polr:2.2.0 motius/polr:latest
      - run:
          name: Push to hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push motius/polr:2.2.0
            docker push motius/polr:latest

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-nginx
      - build-bareos
      - build-polr
      - build-nextcloud:
          requires:
            - build-nginx
