#!/bin/bash

set -e # Exit if any command errors

# Copy default config if not exists
[ ! -e /etc/bareos/${BAREOS_DIR_CONF_FILE} ] && cp /temp/conf/bareos-dir.conf /etc/bareos/bareos-dir.conf
[ ! -e /etc/bareos/bareos-dir.d/schedule/schedules.conf ] && cp /temp/conf/schedules.conf /etc/bareos/bareos-dir.d/schedule/schedules.conf
[ ! -e /etc/bareos/bareos-dir.d/messages/messages.conf ] && cp /temp/conf/messages.conf /etc/bareos/bareos-dir.d/messages/messages.conf
[ ! -e /etc/bareos/bareos-dir.d/catalog/catalog.conf ] && cp /temp/conf/catalog.conf /etc/bareos/bareos-dir.d/catalog/catalog.conf
[ ! -e /etc/bareos/bareos-dir.d/console/access.conf ] && cp /temp/conf/access.conf /etc/bareos/bareos-dir.d/console/access.conf
[ ! -e /etc/bareos/bootstraps ] && mkdir -p /etc/bareos/bootstraps

# Database initialization
./init_db.sh

# Get certificates
./certs.sh

# Configure the recipients
if [[ -z "$SMTP_RECIPIENTS" && -z "$SMTP_OPERATORS" ]]
then
    echo "Please configure 'SMTP_RECIPIENTS' and 'SMTP_OPERATORS'"
    exit 1
else
    echo "Configuring Messages.conf with correct recipients ..."
    sed -i "s/SMTP_RECIPIENTS/$SMTP_RECIPIENTS/g" /etc/bareos/bareos-dir.d/messages/messages.conf
    sed -i "s/SMTP_OPERATORS/$SMTP_OPERATORS/g" /etc/bareos/bareos-dir.d/messages/messages.conf
fi
if [[ -z "$DB_HOST" && -z "$DB_PORT" && -z "$DB_NAME" && -z "$DB_USER" && -z "$DB_PASS" ]]
then
    echo "Please configure 'DB_HOST', 'DB_PORT', 'DB_NAME', 'DB_USER' and 'DB_PASS'"
    exit 1
else
    echo "Configuring Catalog connection ... "
    sed -i "s/DB_HOST/$DB_HOST/g" /etc/bareos/bareos-dir.d/catalog/catalog.conf
    sed -i "s/DB_PORT/$DB_PORT/g" /etc/bareos/bareos-dir.d/catalog/catalog.conf
    sed -i "s/DB_NAME/$DB_NAME/g" /etc/bareos/bareos-dir.d/catalog/catalog.conf
    sed -i "s/DB_USER/$DB_USER/g" /etc/bareos/bareos-dir.d/catalog/catalog.conf
    sed -i "s/DB_PASS/$DB_PASS/g" /etc/bareos/bareos-dir.d/catalog/catalog.conf
fi
# Config test
/usr/sbin/bareos-dir -t -c /etc/bareos/${BAREOS_DIR_CONF_FILE}

# (tail -F /var/log/bareos/bareos.log 2>/dev/null 1>/dev/stdout)&
echo "Starting Bareos Dir"
exec /usr/sbin/bareos-dir -f -c /etc/bareos/${BAREOS_DIR_CONF_FILE} -d 200
